// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EventsourceRecord eventsource record
//
// swagger:model eventsource.Record
type EventsourceRecord struct {

	// aggregate Id
	AggregateID string `json:"aggregateId,omitempty"`

	// data
	Data []int64 `json:"data"`

	// sequence Id
	SequenceID string `json:"sequenceId,omitempty"`

	// timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this eventsource record
func (m *EventsourceRecord) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventsourceRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventsourceRecord) UnmarshalBinary(b []byte) error {
	var res EventsourceRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
