// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WebmodelsNodeCount webmodels node count
//
// swagger:model webmodels.NodeCount
type WebmodelsNodeCount struct {

	// node count
	NodeCount int64 `json:"nodeCount,omitempty"`
}

// Validate validates this webmodels node count
func (m *WebmodelsNodeCount) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WebmodelsNodeCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebmodelsNodeCount) UnmarshalBinary(b []byte) error {
	var res WebmodelsNodeCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
