// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WebmodelsAssetTaxonomy webmodels asset taxonomy
//
// swagger:model webmodels.AssetTaxonomy
type WebmodelsAssetTaxonomy struct {

	// asset taxonomy
	AssetTaxonomy *WebmodelsAssetClasses `json:"assetTaxonomy,omitempty"`
}

// Validate validates this webmodels asset taxonomy
func (m *WebmodelsAssetTaxonomy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssetTaxonomy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WebmodelsAssetTaxonomy) validateAssetTaxonomy(formats strfmt.Registry) error {

	if swag.IsZero(m.AssetTaxonomy) { // not required
		return nil
	}

	if m.AssetTaxonomy != nil {
		if err := m.AssetTaxonomy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("assetTaxonomy")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WebmodelsAssetTaxonomy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebmodelsAssetTaxonomy) UnmarshalBinary(b []byte) error {
	var res WebmodelsAssetTaxonomy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
