// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/SKF/go-utility/v2/uuid"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WebmodelsComponentInput webmodels component input
//
// swagger:model webmodels.ComponentInput
type WebmodelsComponentInput struct {

	// attached to
	AttachedTo uuid.UUID `json:"attachedTo,omitempty"`

	// designation
	Designation string `json:"designation,omitempty"`

	// fixed speed
	FixedSpeed float64 `json:"fixedSpeed,omitempty"`

	// id
	ID uuid.UUID `json:"id,omitempty"`

	// manufacturer
	Manufacturer string `json:"manufacturer,omitempty"`

	// position
	Position int64 `json:"position,omitempty"`

	// position description
	PositionDescription string `json:"positionDescription,omitempty"`

	// rotating ring
	// Enum: [inner outer both]
	RotatingRing string `json:"rotatingRing,omitempty"`

	// serial number
	SerialNumber string `json:"serialNumber,omitempty"`

	// shaft side
	// Enum: [de nde unknown]
	ShaftSide string `json:"shaftSide,omitempty"`

	// type
	// Enum: [shaft bearing]
	Type string `json:"type,omitempty"`
}

// Validate validates this webmodels component input
func (m *WebmodelsComponentInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRotatingRing(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateShaftSide(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var webmodelsComponentInputTypeRotatingRingPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["inner","outer","both"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		webmodelsComponentInputTypeRotatingRingPropEnum = append(webmodelsComponentInputTypeRotatingRingPropEnum, v)
	}
}

const (

	// WebmodelsComponentInputRotatingRingInner captures enum value "inner"
	WebmodelsComponentInputRotatingRingInner string = "inner"

	// WebmodelsComponentInputRotatingRingOuter captures enum value "outer"
	WebmodelsComponentInputRotatingRingOuter string = "outer"

	// WebmodelsComponentInputRotatingRingBoth captures enum value "both"
	WebmodelsComponentInputRotatingRingBoth string = "both"
)

// prop value enum
func (m *WebmodelsComponentInput) validateRotatingRingEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, webmodelsComponentInputTypeRotatingRingPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WebmodelsComponentInput) validateRotatingRing(formats strfmt.Registry) error {

	if swag.IsZero(m.RotatingRing) { // not required
		return nil
	}

	// value enum
	if err := m.validateRotatingRingEnum("rotatingRing", "body", m.RotatingRing); err != nil {
		return err
	}

	return nil
}

var webmodelsComponentInputTypeShaftSidePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["de","nde","unknown"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		webmodelsComponentInputTypeShaftSidePropEnum = append(webmodelsComponentInputTypeShaftSidePropEnum, v)
	}
}

const (

	// WebmodelsComponentInputShaftSideDe captures enum value "de"
	WebmodelsComponentInputShaftSideDe string = "de"

	// WebmodelsComponentInputShaftSideNde captures enum value "nde"
	WebmodelsComponentInputShaftSideNde string = "nde"

	// WebmodelsComponentInputShaftSideUnknown captures enum value "unknown"
	WebmodelsComponentInputShaftSideUnknown string = "unknown"
)

// prop value enum
func (m *WebmodelsComponentInput) validateShaftSideEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, webmodelsComponentInputTypeShaftSidePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WebmodelsComponentInput) validateShaftSide(formats strfmt.Registry) error {

	if swag.IsZero(m.ShaftSide) { // not required
		return nil
	}

	// value enum
	if err := m.validateShaftSideEnum("shaftSide", "body", m.ShaftSide); err != nil {
		return err
	}

	return nil
}

var webmodelsComponentInputTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["shaft","bearing"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		webmodelsComponentInputTypeTypePropEnum = append(webmodelsComponentInputTypeTypePropEnum, v)
	}
}

const (

	// WebmodelsComponentInputTypeShaft captures enum value "shaft"
	WebmodelsComponentInputTypeShaft string = "shaft"

	// WebmodelsComponentInputTypeBearing captures enum value "bearing"
	WebmodelsComponentInputTypeBearing string = "bearing"
)

// prop value enum
func (m *WebmodelsComponentInput) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, webmodelsComponentInputTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WebmodelsComponentInput) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WebmodelsComponentInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebmodelsComponentInput) UnmarshalBinary(b []byte) error {
	var res WebmodelsComponentInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
