// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WebmodelsNodeIDs webmodels node i ds
//
// swagger:model webmodels.NodeIDs
type WebmodelsNodeIDs struct {

	// node ids
	NodeIds []string `json:"nodeIds"`
}

// Validate validates this webmodels node i ds
func (m *WebmodelsNodeIDs) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WebmodelsNodeIDs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebmodelsNodeIDs) UnmarshalBinary(b []byte) error {
	var res WebmodelsNodeIDs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
