name: Building

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
     matrix:
      ModelDir: [rest/models/, v2/rest/models/]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate
        env:
          MODELDIR: ${{matrix.ModelDir}}
        run: make $MODELDIR

      - name: Build
        env:
          MODELDIR: ${{matrix.ModelDir}}
        run: |
          if ${{ env.MODELDIR != 'rest/models/' }} then
            cd $MODELDIR
            go build -v ./...
          else
            go build -v ./...
          fi

      - name: Test
        run: |
          if ${{ env.MODELDIR != 'rest/models/' }} then
            cd $MODELDIR
            go build -v ./...
          else
            go build -v ./...
          fi