name: Building v2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate
        run: make v2/rest/models/

      - name: Build
        run: cd v2 && go build -v ./...

      - name: Test
        run: cd v2 && go test -v ./...
